# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-20 19:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='blog',
            new_name='Post',
        ),
    ]
